# Generated by Django 5.1.3 on 2024-11-16 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('permisos', models.CharField(blank=True, max_length=50, null=True)),
                ('fono', models.BigIntegerField(blank=True, null=True)),
                ('mail', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id_cita', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('hora', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cita',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'estado',
            },
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id_historial', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('edad', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'historial',
            },
        ),
        migrations.CreateModel(
            name='MetodoDePago',
            fields=[
                ('id_metodo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'metodo_de_pago',
            },
        ),
        migrations.CreateModel(
            name='Prevision',
            fields=[
                ('id_prevision', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('cobertura', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'prevision',
            },
        ),
        migrations.CreateModel(
            name='Reportes',
            fields=[
                ('id_reporte', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fechainicio', models.DateField(blank=True, null=True)),
                ('fechafin', models.DateField(blank=True, null=True)),
                ('ingresos', models.BigIntegerField(blank=True, null=True)),
                ('total', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id_sala', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('numero', models.BigIntegerField(blank=True, null=True)),
                ('capacidad', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sala',
            },
        ),
        migrations.CreateModel(
            name='Administrativo',
            fields=[
                ('rut', models.OneToOneField(db_column='rut', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='avanti.usuario')),
                ('cargo', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'administrativo',
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('rut', models.OneToOneField(db_column='rut', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='avanti.usuario')),
                ('especialidad', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'medico',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('rut', models.OneToOneField(db_column='rut', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='avanti.usuario')),
            ],
            options={
                'db_table': 'paciente',
            },
        ),
        migrations.CreateModel(
            name='Bono',
            fields=[
                ('id_bono', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('monto', models.BigIntegerField(blank=True, null=True)),
                ('feccreacion', models.DateField(blank=True, null=True)),
                ('fecvigencia', models.DateField(blank=True, null=True)),
                ('id_cita', models.ForeignKey(db_column='id_cita', on_delete=django.db.models.deletion.CASCADE, to='avanti.cita')),
                ('id_prevision', models.ForeignKey(db_column='id_prevision', on_delete=django.db.models.deletion.CASCADE, related_name='bonos', to='avanti.prevision')),
                ('id_reporte', models.ForeignKey(db_column='id_reporte', on_delete=django.db.models.deletion.CASCADE, to='avanti.reportes')),
                ('administrativo_rut', models.ForeignKey(db_column='administrativo_rut', on_delete=django.db.models.deletion.CASCADE, to='avanti.administrativo')),
                ('paciente_rut', models.ForeignKey(db_column='paciente_rut', on_delete=django.db.models.deletion.CASCADE, related_name='bonos', to='avanti.paciente')),
            ],
            options={
                'db_table': 'bono',
                'unique_together': {('id_bono', 'id_reporte', 'administrativo_rut')},
            },
        ),
        migrations.CreateModel(
            name='EnfermedadesBase',
            fields=[
                ('id_enfbase', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('id_historial', models.ForeignKey(db_column='id_historial', on_delete=django.db.models.deletion.CASCADE, to='avanti.historial')),
            ],
            options={
                'db_table': 'enfermedades_base',
            },
        ),
        migrations.CreateModel(
            name='Alergias',
            fields=[
                ('id_alergias', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('id_historial', models.ForeignKey(db_column='id_historial', on_delete=django.db.models.deletion.CASCADE, to='avanti.historial')),
            ],
            options={
                'db_table': 'alergias',
            },
        ),
        migrations.AddField(
            model_name='cita',
            name='id_prevision',
            field=models.ForeignKey(db_column='id_prevision', on_delete=django.db.models.deletion.CASCADE, to='avanti.prevision'),
        ),
        migrations.AddField(
            model_name='cita',
            name='id_sala',
            field=models.ForeignKey(db_column='id_sala', on_delete=django.db.models.deletion.CASCADE, to='avanti.sala'),
        ),
        migrations.AddField(
            model_name='reportes',
            name='administrativo_rut',
            field=models.ForeignKey(db_column='administrativo_rut', on_delete=django.db.models.deletion.DO_NOTHING, to='avanti.administrativo'),
        ),
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('fecha', models.DateField(blank=True, null=True)),
                ('horainicio', models.DateTimeField(blank=True, null=True)),
                ('horafin', models.DateTimeField(blank=True, null=True)),
                ('medico_rut', models.OneToOneField(db_column='medico_rut', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='avanti.medico')),
            ],
            options={
                'db_table': 'disponibilidad',
            },
        ),
        migrations.AddField(
            model_name='cita',
            name='medico_rut',
            field=models.ForeignKey(db_column='medico_rut', on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='avanti.medico'),
        ),
        migrations.AddField(
            model_name='historial',
            name='paciente_rut',
            field=models.OneToOneField(db_column='paciente_rut', on_delete=django.db.models.deletion.CASCADE, to='avanti.paciente'),
        ),
        migrations.AddField(
            model_name='cita',
            name='paciente_rut',
            field=models.ForeignKey(db_column='paciente_rut', on_delete=django.db.models.deletion.CASCADE, to='avanti.paciente'),
        ),
        migrations.CreateModel(
            name='Diagnosticos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_diagnostico', models.CharField(max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('id_historial', models.ForeignKey(db_column='id_historial', on_delete=django.db.models.deletion.CASCADE, to='avanti.historial')),
            ],
            options={
                'db_table': 'diagnosticos',
                'unique_together': {('id_diagnostico', 'id_historial')},
            },
        ),
        migrations.CreateModel(
            name='Medicamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_medicamentos', models.CharField(max_length=20)),
                ('nombre', models.TextField(blank=True, null=True)),
                ('id_historial', models.ForeignKey(db_column='id_historial', on_delete=django.db.models.deletion.CASCADE, to='avanti.historial')),
            ],
            options={
                'db_table': 'medicamentos',
                'unique_together': {('id_medicamentos', 'id_historial')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='reportes',
            unique_together={('id_reporte', 'administrativo_rut')},
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pago', models.CharField(max_length=20)),
                ('monto', models.BigIntegerField(blank=True, null=True)),
                ('fechapago', models.DateField(blank=True, null=True)),
                ('id_bono', models.ForeignKey(db_column='id_bono', on_delete=django.db.models.deletion.CASCADE, to='avanti.bono')),
                ('id_metodo', models.ForeignKey(db_column='id_metodo', on_delete=django.db.models.deletion.CASCADE, to='avanti.metododepago')),
                ('id_reporte', models.ForeignKey(db_column='id_reporte', on_delete=django.db.models.deletion.CASCADE, related_name='pago_id_reporte_set', to='avanti.reportes')),
                ('administrativo_rut', models.ForeignKey(db_column='administrativo_rut', on_delete=django.db.models.deletion.CASCADE, related_name='pago_administrativo_rut_set', to='avanti.administrativo')),
            ],
            options={
                'db_table': 'pago',
                'unique_together': {('id_pago', 'id_bono', 'id_reporte', 'administrativo_rut', 'id_metodo')},
            },
        ),
        migrations.CreateModel(
            name='HistorialEstado',
            fields=[
                ('id_historialestado', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fechacambio', models.DateField(blank=True, null=True)),
                ('id_cita', models.ForeignKey(db_column='id_cita', on_delete=django.db.models.deletion.CASCADE, to='avanti.cita')),
                ('id_estado', models.ForeignKey(db_column='id_estado', on_delete=django.db.models.deletion.CASCADE, to='avanti.estado')),
                ('id_prevision', models.ForeignKey(db_column='id_prevision', on_delete=django.db.models.deletion.CASCADE, related_name='historialestado_prevision_set', to='avanti.prevision')),
                ('paciente_rut', models.ForeignKey(db_column='paciente_rut', on_delete=django.db.models.deletion.CASCADE, related_name='historialestado_paciente_set', to='avanti.paciente')),
            ],
            options={
                'db_table': 'historial_estado',
                'constraints': [models.UniqueConstraint(fields=('id_historialestado', 'id_estado', 'id_cita', 'id_prevision', 'paciente_rut'), name='unique_historialestado')],
            },
        ),
        migrations.AlterUniqueTogether(
            name='cita',
            unique_together={('id_cita', 'paciente_rut', 'id_prevision')},
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('fecha', models.DateField(blank=True, null=True)),
                ('horainicio', models.DateTimeField(blank=True, null=True)),
                ('horafin', models.DateTimeField(blank=True, null=True)),
                ('medico_rut', models.OneToOneField(db_column='medico_rut', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='avanti.disponibilidad')),
                ('id_sala', models.ForeignKey(db_column='id_sala', on_delete=django.db.models.deletion.CASCADE, to='avanti.sala')),
            ],
            options={
                'db_table': 'horario',
                'unique_together': {('medico_rut', 'id_sala')},
            },
        ),
    ]
