# Generated by Django 5.1.1 on 2024-12-08 21:01

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('fono', models.BigIntegerField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('cita', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'cita',
            },
        ),
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('disponibilidad', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('dia', models.CharField(choices=[('L', 'Lunes'), ('M', 'Martes'), ('X', 'Miércoles'), ('J', 'Jueves'), ('V', 'Viernes'), ('S', 'Sábado'), ('D', 'Domingo')], default='L', max_length=1)),
                ('horainicio', models.TimeField(blank=True, null=True)),
                ('horafin', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'disponibilidad',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('estado', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'estado',
            },
        ),
        migrations.CreateModel(
            name='FichaClinica',
            fields=[
                ('id_ficha', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ficha_clinica',
            },
        ),
        migrations.CreateModel(
            name='MetodoDePago',
            fields=[
                ('metodo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'metodo_de_pago',
            },
        ),
        migrations.CreateModel(
            name='Prevision',
            fields=[
                ('prevision', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('cobertura', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'prevision',
            },
        ),
        migrations.CreateModel(
            name='Reportes',
            fields=[
                ('reporte', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fechainicio', models.DateField(blank=True, null=True)),
                ('fechafin', models.DateField(blank=True, null=True)),
                ('ingresos', models.BigIntegerField(blank=True, null=True)),
                ('total', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('sala', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('numero', models.BigIntegerField(blank=True, null=True)),
                ('capacidad', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sala',
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('sucursal', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.TextField()),
            ],
            options={
                'db_table': 'sucursal',
            },
        ),
        migrations.CreateModel(
            name='Administrativo',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cargo', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'administrativo',
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('especialidad', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'medico',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'paciente',
            },
        ),
        migrations.CreateModel(
            name='Bono',
            fields=[
                ('bono', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('monto', models.BigIntegerField(blank=True, null=True)),
                ('feccreacion', models.DateField(blank=True, null=True)),
                ('fecvigencia', models.DateField(blank=True, null=True)),
                ('cita', models.ForeignKey(db_column='id_cita', on_delete=django.db.models.deletion.CASCADE, to='avanti.cita')),
                ('prevision', models.ForeignKey(db_column='id_prevision', on_delete=django.db.models.deletion.CASCADE, related_name='bonos', to='avanti.prevision')),
                ('reporte', models.ForeignKey(db_column='id_reporte', on_delete=django.db.models.deletion.CASCADE, to='avanti.reportes')),
                ('administrativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avanti.administrativo')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonos', to='avanti.paciente')),
            ],
            options={
                'db_table': 'bono',
                'unique_together': {('bono', 'reporte', 'administrativo')},
            },
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('historial', models.AutoField(primary_key=True, serialize=False)),
                ('edad', models.BigIntegerField(blank=True, null=True)),
                ('ficha_clinica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='avanti.fichaclinica')),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='avanti.paciente')),
            ],
            options={
                'db_table': 'historial',
            },
        ),
        migrations.CreateModel(
            name='EnfermedadesBase',
            fields=[
                ('enfbase', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('historial', models.ForeignKey(db_column='id_historial', on_delete=django.db.models.deletion.CASCADE, to='avanti.historial')),
            ],
            options={
                'db_table': 'enfermedades_base',
            },
        ),
        migrations.CreateModel(
            name='Diagnosticos',
            fields=[
                ('diagnostico', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('historial', models.ForeignKey(db_column='id_historial', on_delete=django.db.models.deletion.CASCADE, to='avanti.historial')),
            ],
            options={
                'db_table': 'diagnosticos',
            },
        ),
        migrations.CreateModel(
            name='Alergias',
            fields=[
                ('alergias', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('historial', models.ForeignKey(db_column='id_historial', on_delete=django.db.models.deletion.CASCADE, to='avanti.historial')),
            ],
            options={
                'db_table': 'alergias',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('horario', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('fechainicio', models.DateTimeField(blank=True, null=True)),
                ('fechafin', models.DateTimeField(blank=True, null=True)),
                ('disponible', models.BooleanField(default=True)),
                ('disponibilidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='avanti.disponibilidad')),
                ('sala', models.ForeignKey(db_column='id_sala', on_delete=django.db.models.deletion.CASCADE, to='avanti.sala')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avanti.medico')),
            ],
            options={
                'db_table': 'horario',
                'unique_together': {('sala', 'medico', 'fechainicio', 'fechafin')},
            },
        ),
        migrations.AddField(
            model_name='cita',
            name='horario',
            field=models.ForeignKey(db_column='id_horario', on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='avanti.horario'),
        ),
        migrations.CreateModel(
            name='Medicamentos',
            fields=[
                ('medicamentos', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(blank=True, null=True)),
                ('historial', models.ForeignKey(db_column='id_historial', on_delete=django.db.models.deletion.CASCADE, to='avanti.historial')),
            ],
            options={
                'db_table': 'medicamentos',
            },
        ),
        migrations.AddField(
            model_name='cita',
            name='prevision',
            field=models.ForeignKey(db_column='id_prevision', on_delete=django.db.models.deletion.CASCADE, to='avanti.prevision'),
        ),
        migrations.AddField(
            model_name='sala',
            name='sucursal',
            field=models.ForeignKey(db_column='id_sucursal', on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='avanti.sucursal'),
        ),
        migrations.AddField(
            model_name='reportes',
            name='administrativo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='avanti.administrativo'),
        ),
        migrations.AddField(
            model_name='disponibilidad',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avanti.medico'),
        ),
        migrations.AddField(
            model_name='fichaclinica',
            name='paciente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='avanti.paciente'),
        ),
        migrations.AddField(
            model_name='cita',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avanti.paciente'),
        ),
        migrations.AlterUniqueTogether(
            name='reportes',
            unique_together={('reporte', 'administrativo')},
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pago', models.CharField(max_length=20)),
                ('monto', models.BigIntegerField(blank=True, null=True)),
                ('fechapago', models.DateField(blank=True, null=True)),
                ('bono', models.ForeignKey(db_column='id_bono', on_delete=django.db.models.deletion.CASCADE, to='avanti.bono')),
                ('metodo', models.ForeignKey(db_column='id_metodo', on_delete=django.db.models.deletion.CASCADE, to='avanti.metododepago')),
                ('reporte', models.ForeignKey(db_column='id_reporte', on_delete=django.db.models.deletion.CASCADE, related_name='pago_id_reporte_set', to='avanti.reportes')),
                ('administrativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avanti.administrativo')),
            ],
            options={
                'db_table': 'pago',
                'unique_together': {('pago', 'bono', 'reporte', 'administrativo', 'metodo')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='disponibilidad',
            unique_together={('medico', 'dia', 'horainicio', 'horafin')},
        ),
        migrations.CreateModel(
            name='HistorialEstado',
            fields=[
                ('historialestado', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fechacambio', models.DateField(blank=True, null=True)),
                ('cita', models.ForeignKey(db_column='id_cita', on_delete=django.db.models.deletion.CASCADE, to='avanti.cita')),
                ('estado', models.ForeignKey(db_column='id_estado', on_delete=django.db.models.deletion.CASCADE, to='avanti.estado')),
                ('prevision', models.ForeignKey(db_column='prevision', on_delete=django.db.models.deletion.CASCADE, related_name='historialestado_prevision_set', to='avanti.prevision')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avanti.paciente')),
            ],
            options={
                'db_table': 'historial_estado',
                'constraints': [models.UniqueConstraint(fields=('historialestado', 'estado', 'cita', 'prevision', 'paciente'), name='unique_historialestado')],
            },
        ),
        migrations.AlterUniqueTogether(
            name='cita',
            unique_together={('cita', 'paciente', 'prevision')},
        ),
    ]
