# Generated by Django 5.1.3 on 2024-11-25 02:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('fono', models.BigIntegerField(blank=True, null=True)),
                ('mail', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('cita', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('hora', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cita',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('estado', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'estado',
            },
        ),
        migrations.CreateModel(
            name='FichaClinica',
            fields=[
                ('id_ficha', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ficha_clinica',
            },
        ),
        migrations.CreateModel(
            name='MetodoDePago',
            fields=[
                ('metodo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'metodo_de_pago',
            },
        ),
        migrations.CreateModel(
            name='Prevision',
            fields=[
                ('prevision', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('cobertura', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'prevision',
            },
        ),
        migrations.CreateModel(
            name='Reportes',
            fields=[
                ('reporte', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fechainicio', models.DateField(blank=True, null=True)),
                ('fechafin', models.DateField(blank=True, null=True)),
                ('ingresos', models.BigIntegerField(blank=True, null=True)),
                ('total', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('sala', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('numero', models.BigIntegerField(blank=True, null=True)),
                ('capacidad', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sala',
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('sucursal', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.TextField()),
            ],
            options={
                'db_table': 'sucursal',
            },
        ),
        migrations.CreateModel(
            name='Administrativo',
            fields=[
                ('rut', models.OneToOneField(db_column='rut', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='avanti.usuario')),
                ('cargo', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'administrativo',
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('rut', models.OneToOneField(db_column='rut', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='avanti.usuario')),
                ('especialidad', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'medico',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('rut', models.OneToOneField(db_column='rut', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='avanti.usuario')),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'paciente',
            },
        ),
        migrations.CreateModel(
            name='Bono',
            fields=[
                ('bono', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('monto', models.BigIntegerField(blank=True, null=True)),
                ('feccreacion', models.DateField(blank=True, null=True)),
                ('fecvigencia', models.DateField(blank=True, null=True)),
                ('cita', models.ForeignKey(db_column='id_cita', on_delete=django.db.models.deletion.CASCADE, to='avanti.cita')),
                ('prevision', models.ForeignKey(db_column='id_prevision', on_delete=django.db.models.deletion.CASCADE, related_name='bonos', to='avanti.prevision')),
                ('reporte', models.ForeignKey(db_column='id_reporte', on_delete=django.db.models.deletion.CASCADE, to='avanti.reportes')),
                ('administrativo_rut', models.ForeignKey(db_column='administrativo_rut', on_delete=django.db.models.deletion.CASCADE, to='avanti.administrativo')),
                ('paciente_rut', models.ForeignKey(db_column='paciente_rut', on_delete=django.db.models.deletion.CASCADE, related_name='bonos', to='avanti.paciente')),
            ],
            options={
                'db_table': 'bono',
                'unique_together': {('bono', 'reporte', 'administrativo_rut')},
            },
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('historial', models.AutoField(primary_key=True, serialize=False)),
                ('edad', models.BigIntegerField(blank=True, null=True)),
                ('ficha_clinica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='avanti.fichaclinica')),
                ('paciente_rut', models.OneToOneField(db_column='paciente_rut', on_delete=django.db.models.deletion.CASCADE, to='avanti.paciente')),
            ],
            options={
                'db_table': 'historial',
            },
        ),
        migrations.CreateModel(
            name='EnfermedadesBase',
            fields=[
                ('enfbase', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('historial', models.ForeignKey(db_column='id_historial', on_delete=django.db.models.deletion.CASCADE, to='avanti.historial')),
            ],
            options={
                'db_table': 'enfermedades_base',
            },
        ),
        migrations.CreateModel(
            name='Diagnosticos',
            fields=[
                ('diagnostico', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('historial', models.ForeignKey(db_column='id_historial', on_delete=django.db.models.deletion.CASCADE, to='avanti.historial')),
            ],
            options={
                'db_table': 'diagnosticos',
            },
        ),
        migrations.CreateModel(
            name='Alergias',
            fields=[
                ('alergias', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('historial', models.ForeignKey(db_column='id_historial', on_delete=django.db.models.deletion.CASCADE, to='avanti.historial')),
            ],
            options={
                'db_table': 'alergias',
            },
        ),
        migrations.CreateModel(
            name='Medicamentos',
            fields=[
                ('medicamentos', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(blank=True, null=True)),
                ('historial', models.ForeignKey(db_column='id_historial', on_delete=django.db.models.deletion.CASCADE, to='avanti.historial')),
            ],
            options={
                'db_table': 'medicamentos',
            },
        ),
        migrations.AddField(
            model_name='cita',
            name='prevision',
            field=models.ForeignKey(db_column='id_prevision', on_delete=django.db.models.deletion.CASCADE, to='avanti.prevision'),
        ),
        migrations.AddField(
            model_name='cita',
            name='sala',
            field=models.ForeignKey(db_column='id_sala', on_delete=django.db.models.deletion.CASCADE, to='avanti.sala'),
        ),
        migrations.AddField(
            model_name='cita',
            name='sucursal',
            field=models.ForeignKey(db_column='id_sucursal', on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='avanti.sucursal'),
        ),
        migrations.AddField(
            model_name='reportes',
            name='administrativo_rut',
            field=models.ForeignKey(db_column='administrativo_rut', on_delete=django.db.models.deletion.DO_NOTHING, to='avanti.administrativo'),
        ),
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('disponibilidad', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('dia', models.CharField(choices=[('L', 'Lunes'), ('M', 'Martes'), ('X', 'Miércoles'), ('J', 'Jueves'), ('V', 'Viernes'), ('S', 'Sábado'), ('D', 'Domingo')], default='L', max_length=1)),
                ('horainicio', models.TimeField(blank=True, null=True)),
                ('horafin', models.TimeField(blank=True, null=True)),
                ('medico', models.ForeignKey(db_column='medico_rut', on_delete=django.db.models.deletion.CASCADE, to='avanti.medico')),
            ],
            options={
                'db_table': 'disponibilidad',
                'unique_together': {('medico', 'dia', 'horainicio', 'horafin')},
            },
        ),
        migrations.AddField(
            model_name='cita',
            name='medico_rut',
            field=models.ForeignKey(db_column='medico_rut', on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='avanti.medico'),
        ),
        migrations.AddField(
            model_name='fichaclinica',
            name='paciente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha_clinica', to='avanti.paciente'),
        ),
        migrations.AddField(
            model_name='cita',
            name='paciente_rut',
            field=models.ForeignKey(db_column='paciente_rut', on_delete=django.db.models.deletion.CASCADE, to='avanti.paciente'),
        ),
        migrations.AlterUniqueTogether(
            name='reportes',
            unique_together={('reporte', 'administrativo_rut')},
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pago', models.CharField(max_length=20)),
                ('monto', models.BigIntegerField(blank=True, null=True)),
                ('fechapago', models.DateField(blank=True, null=True)),
                ('bono', models.ForeignKey(db_column='id_bono', on_delete=django.db.models.deletion.CASCADE, to='avanti.bono')),
                ('metodo', models.ForeignKey(db_column='id_metodo', on_delete=django.db.models.deletion.CASCADE, to='avanti.metododepago')),
                ('reporte', models.ForeignKey(db_column='id_reporte', on_delete=django.db.models.deletion.CASCADE, related_name='pago_id_reporte_set', to='avanti.reportes')),
                ('administrativo_rut', models.ForeignKey(db_column='administrativo_rut', on_delete=django.db.models.deletion.CASCADE, related_name='pago_administrativo_rut_set', to='avanti.administrativo')),
            ],
            options={
                'db_table': 'pago',
                'unique_together': {('pago', 'bono', 'reporte', 'administrativo_rut', 'metodo')},
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('horario', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('fechainicio', models.DateTimeField(blank=True, null=True)),
                ('fechafin', models.DateTimeField(blank=True, null=True)),
                ('disponible', models.BooleanField(default=True)),
                ('disponibilidad', models.ManyToManyField(related_name='horarios', to='avanti.disponibilidad')),
                ('sala', models.ForeignKey(db_column='sala', on_delete=django.db.models.deletion.CASCADE, to='avanti.sala')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avanti.medico')),
            ],
            options={
                'db_table': 'horario',
                'unique_together': {('sala', 'medico', 'fechainicio', 'fechafin')},
            },
        ),
        migrations.CreateModel(
            name='HistorialEstado',
            fields=[
                ('historialestado', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fechacambio', models.DateField(blank=True, null=True)),
                ('cita', models.ForeignKey(db_column='id_cita', on_delete=django.db.models.deletion.CASCADE, to='avanti.cita')),
                ('estado', models.ForeignKey(db_column='id_estado', on_delete=django.db.models.deletion.CASCADE, to='avanti.estado')),
                ('prevision', models.ForeignKey(db_column='prevision', on_delete=django.db.models.deletion.CASCADE, related_name='historialestado_prevision_set', to='avanti.prevision')),
                ('paciente_rut', models.ForeignKey(db_column='paciente_rut', on_delete=django.db.models.deletion.CASCADE, related_name='historialestado_paciente_set', to='avanti.paciente')),
            ],
            options={
                'db_table': 'historial_estado',
                'constraints': [models.UniqueConstraint(fields=('historialestado', 'estado', 'cita', 'prevision', 'paciente_rut'), name='unique_historialestado')],
            },
        ),
        migrations.AlterUniqueTogether(
            name='cita',
            unique_together={('cita', 'paciente_rut', 'prevision')},
        ),
    ]
