# Generated by Django 5.1.3 on 2024-12-03 22:09

from django.db import migrations

def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    # Crear grupos
    paciente_group, _ = Group.objects.get_or_create(name='Paciente')
    medico_group, _ = Group.objects.get_or_create(name='Medico')
    padmin_group, _ = Group.objects.get_or_create(name='Personal Administrativo')


    fichaclinica_ct = ContentType.objects.get(app_label='avanti', model='fichaclinica')
    fichaclinica_view = Permission.objects.get(codename='view_fichaclinica', content_type=fichaclinica_ct)
    fichaclinica_add = Permission.objects.get(codename='add_fichaclinica', content_type=fichaclinica_ct)
    fichaclinica_change = Permission.objects.get(codename='change_fichaclinica', content_type=fichaclinica_ct)
    fichaclinica_delete= Permission.objects.get(codename='delete_fichaclinica', content_type=fichaclinica_ct)

    alergias_ct = ContentType.objects.get(app_label='avanti', model='alergias')
    alergias_view = Permission.objects.get(codename='view_alergias', content_type=alergias_ct)
    alergias_add = Permission.objects.get(codename='add_alergias', content_type=alergias_ct)
    alergias_change = Permission.objects.get(codename='change_alergias', content_type=alergias_ct)
    alergias_delete= Permission.objects.get(codename='delete_alergias', content_type=alergias_ct)

    diagnosticos_ct = ContentType.objects.get(app_label='avanti', model='diagnosticos')
    diagnosticos_view = Permission.objects.get(codename='view_diagnosticos', content_type=diagnosticos_ct)
    diagnosticos_add = Permission.objects.get(codename='add_diagnosticos', content_type=diagnosticos_ct)
    diagnosticos_change = Permission.objects.get(codename='change_diagnosticos', content_type=diagnosticos_ct)
    diagnosticos_delete= Permission.objects.get(codename='delete_diagnosticos', content_type=diagnosticos_ct)

    enfermedadesbase_ct = ContentType.objects.get(app_label='avanti', model='enfermedadesbase')
    enfermedadesbase_view = Permission.objects.get(codename='view_enfermedadesbase', content_type=enfermedadesbase_ct)
    enfermedadesbase_add = Permission.objects.get(codename='add_enfermedadesbase', content_type=enfermedadesbase_ct)
    enfermedadesbase_change = Permission.objects.get(codename='change_enfermedadesbase', content_type=enfermedadesbase_ct)
    enfermedadesbase_delete= Permission.objects.get(codename='delete_enfermedadesbase', content_type=enfermedadesbase_ct)

    medicamentos_ct = ContentType.objects.get(app_label='avanti', model='medicamentos')
    medicamentos_view = Permission.objects.get(codename='view_medicamentos', content_type=medicamentos_ct)
    medicamentos_add = Permission.objects.get(codename='add_medicamentos', content_type=medicamentos_ct)
    medicamentos_change = Permission.objects.get(codename='change_medicamentos', content_type=medicamentos_ct)
    medicamentos_delete= Permission.objects.get(codename='delete_medicamentos', content_type=medicamentos_ct)

    disponibilidad_ct = ContentType.objects.get(app_label='avanti', model='disponibilidad')
    disponibilidad_view = Permission.objects.get(codename='view_disponibilidad', content_type=disponibilidad_ct)
    disponibilidad_add = Permission.objects.get(codename='add_disponibilidad', content_type=disponibilidad_ct)
    disponibilidad_change = Permission.objects.get(codename='change_disponibilidad', content_type=disponibilidad_ct)
    disponibilidad_delete= Permission.objects.get(codename='delete_disponibilidad', content_type=disponibilidad_ct)

    horario_ct = ContentType.objects.get(app_label='avanti', model='horario')
    horario_view = Permission.objects.get(codename='view_horario', content_type=horario_ct)
    horario_add = Permission.objects.get(codename='add_horario', content_type=horario_ct)
    horario_change = Permission.objects.get(codename='change_horario', content_type=horario_ct)
    horario_delete= Permission.objects.get(codename='delete_horario', content_type=horario_ct)

    cita_ct = ContentType.objects.get(app_label='avanti', model='cita')
    cita_view = Permission.objects.get(codename='view_cita', content_type=cita_ct)
    cita_add = Permission.objects.get(codename='add_cita', content_type=cita_ct)
    cita_change = Permission.objects.get(codename='change_cita', content_type=cita_ct)
    cita_delete= Permission.objects.get(codename='delete_cita', content_type=cita_ct)

    sala_ct = ContentType.objects.get(app_label='avanti', model='sala')
    sala_view = Permission.objects.get(codename='view_sala', content_type=sala_ct)
    sala_add = Permission.objects.get(codename='add_sala', content_type=sala_ct)
    sala_change = Permission.objects.get(codename='change_sala', content_type=sala_ct)
    sala_delete= Permission.objects.get(codename='delete_sala', content_type=sala_ct)

    bono_ct = ContentType.objects.get(app_label='avanti', model='bono')
    bono_view = Permission.objects.get(codename='view_bono', content_type=bono_ct)
    bono_add = Permission.objects.get(codename='add_bono', content_type=bono_ct)
    bono_change = Permission.objects.get(codename='change_bono', content_type=bono_ct)
    bono_delete= Permission.objects.get(codename='delete_bono', content_type=bono_ct)

    reportes_ct = ContentType.objects.get(app_label='avanti', model='reportes')
    reportes_view = Permission.objects.get(codename='view_reportes', content_type=reportes_ct)
    reportes_add = Permission.objects.get(codename='add_reportes', content_type=reportes_ct)
    reportes_change = Permission.objects.get(codename='change_reportes', content_type=reportes_ct)
    reportes_delete= Permission.objects.get(codename='delete_reportes', content_type=reportes_ct)

    pago_ct = ContentType.objects.get(app_label='avanti', model='pago')
    pago_view = Permission.objects.get(codename='view_pago', content_type=pago_ct)
    pago_add = Permission.objects.get(codename='add_pago', content_type=pago_ct)
    pago_change = Permission.objects.get(codename='change_pago', content_type=pago_ct)
    pago_delete= Permission.objects.get(codename='delete_pago', content_type=pago_ct)

    

    medico_group.permissions.add(
        fichaclinica_view,fichaclinica_add,
        fichaclinica_change,fichaclinica_delete,
        alergias_view,alergias_delete,
        alergias_add,alergias_change,
        diagnosticos_add,diagnosticos_change,
        diagnosticos_view, diagnosticos_delete,
        enfermedadesbase_add,enfermedadesbase_delete,
        enfermedadesbase_change,enfermedadesbase_view,
        medicamentos_add,medicamentos_change,
        medicamentos_view,medicamentos_delete,
        horario_view,horario_change,cita_view,
        cita_change,
        )

    padmin_group.permissions.add(
        horario_change,horario_add,horario_view,
        horario_delete,disponibilidad_add,disponibilidad_change,
        disponibilidad_view,disponibilidad_delete,
        cita_view,sala_add,sala_change,sala_view,
        sala_delete,pago_add,pago_change,pago_delete,
        pago_view,bono_add,bono_change,bono_delete,
        bono_view, reportes_add,reportes_change,
        reportes_delete,reportes_view,
    )

    paciente_group.permissions.add(
        cita_add,cita_change,cita_view,cita_delete,
        bono_view,fichaclinica_view,alergias_view,
        diagnosticos_view,enfermedadesbase_view,medicamentos_view,
        horario_view, pago_view
    )

class Migration(migrations.Migration):

    dependencies = [
        ('avanti', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_groups),
    ]
