# Generated by Django 5.1.3 on 2024-11-28 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avanti', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='cita',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
