# Generated by Django 5.1.1 on 2024-12-08 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avanti', '0002_addgroups'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
            ],
        ),
    ]
