# Generated by Django 5.1.1 on 2024-12-21 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avanti', '0003_cargar_datos'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='finalizada',
            field=models.BooleanField(default=False),
        ),
    ]
