# Generated by Django 5.1.1 on 2024-12-12 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avanti', '0004_alter_administrativo_usuario_alter_medico_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historial',
            name='paciente',
        ),
    ]
