
from .administrativo import Administrativo
from .alergias import Alergias
from .bono import Bono
from .cita import Cita
from .diagnosticos import Diagnosticos
from .disponibilidad import Disponibilidad
from .enfermedadesbase import EnfermedadesBase
from .estado import Estado
from .historial import Historial
from .historialestado import HistorialEstado
from .horario import Horario
from .medicamentos import Medicamentos
from .medico import Medico
from .metododepago import MetodoDePago
from .paciente import Paciente
from .pago import Pago
from .prevision import Prevision
from .reportes import Reportes
from .sala import Sala
from .usuario import Usuario