
from .administrativo import Administrativo
from .alergias import Alergia
from .bono import Bono
from .cita import Cita
from .diagnosticos import Diagnostico
from .disponibilidad import Disponibilidad
from .enfermedadesbase import EnfermedadesBase
from .estado import Estado
from .historial import Historial
from .historialestado import HistorialEstado
from .horario import Horario
from .medicamentos import Medicamento
from .medico import Medico
from .metododepago import MetodoDePago
from .paciente import Paciente
from .pago import Pago
from .prevision import Prevision
from .reportes import Reportes
from .sala import Sala
from .sucursal import Sucursal
from .usuario import Usuario
from .fichaclinica import FichaClinica
from .consulta import Consulta
from .especialidad import Especialidad